# k8s/frontend-deployment.yaml

# Définition du namespace (à conserver si non déjà créé ailleurs)
apiVersion: v1
kind: Namespace
metadata:
  name: bibliotheque
---
# Déploiement de l'application frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibliotheque-frontend
  namespace: bibliotheque
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bibliotheque-frontend
  template:
    metadata:
      labels:
        app: bibliotheque-frontend
    spec:
      containers:
      - name: frontend
        image: touatifadwa/bibliotheque-frontend:latest
        ports:
        - containerPort: 80
---
# Service NodePort pour exposer le frontend
apiVersion: v1
kind: Service
metadata:
  name: bibliotheque-frontend-service
  namespace: bibliotheque
spec:
  type: NodePort
  selector:
    app: bibliotheque-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
