# k8s/frontend-deployment.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: bibliotheque1
  labels:
    app: bibliotheque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibliotheque-frontend
  namespace: bibliotheque
  labels:
    app: bibliotheque
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bibliotheque-frontend
  template:
    metadata:
      labels:
        app: bibliotheque-frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: touatifadwa/bibliotheque-frontend:latest  # À remplacer par ${{ github.sha }} en CI/CD
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bibliotheque-frontend-service
  namespace: bibliotheque
spec:
  type: NodePort
  selector:
    app: bibliotheque-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Port exposé sur le nœud (30000-32767)
